version: '3.1'
services:
  web:
    build:  
      context: .
      dockerfile: Dockerfile
    ports:
    - 8080:80
    volumes:
    - ./src:/var/www/html

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      

